### ISSUE TITLE
conekta android: charge request failure

### ISSUE THREAD

**Issue by Dcodechef** [javikin/conekta-android#1]
Hi Javikin,

I were trying to test conekta android sample before implementing that in our app, But I got error in charge bank fragment. I paste log in below,
Please help me, Thanks in Advance.

Android code block:
 btnAsync.setOnClickListener(new View.OnClickListener() {
            public void onClick(View view) {
                pd.show();
                Conekta.charge(ChargeBankFragment.this.getActivity(), chargeCard, new JsonHttpResponseHandler() {

 Log is

.androidJSInterface.getString((function(){try{return (function () { var plugins_string='', i=0; for (p=navigator.plugins[0]; i< navigator.plugins.length;p=navigator.plugins[i++]) {  plugins_string += p.name + '<FIELD_SEP>' + p.description + '<FIELD_SEP>' + p.filename + '<FIELD_SEP>' + p.length.toString() + '<REC_SEP>'; } return plugins_string;})(); + "";}catch(js_eval_err){return '';}})());
01-30 10:50:50.403    6929-6929/com.startxlabs.conektademo D/AndroidRuntime﹕ Shutting down VM
    --------- beginning of crash
01-30 10:50:50.407    6929-6929/com.startxlabs.conektademo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.startxlabs.conektademo, PID: 6929
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.concurrent.CountDownLatch.await(long, java.util.concurrent.TimeUnit)' on a null object reference
            at com.threatmetrix.TrustDefenderMobile.JSExecutor.getJSResult(JSExecutor.java:145)
            at com.threatmetrix.TrustDefenderMobile.TrustDefenderMobile.getBrowserInfo(TrustDefenderMobile.java:809)
            at com.threatmetrix.TrustDefenderMobile.TrustDefenderMobile.access$300(TrustDefenderMobile.java:46)
            at com.threatmetrix.TrustDefenderMobile.TrustDefenderMobile$1.run(TrustDefenderMobile.java:1124)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
01-30 10:50:55.672    6929-6961/com.startxlabs.conektademo D/com.threatmetrix.TrustDefenderMobile.TrustDefenderMobile﹕ profile request complete
01-30 10:50:55.672    6929-6961/com.startxlabs.conektademo D/com.threatmetrix.TrustDefenderMobile.TrustDefenderMobile﹕ getStatus returns: THM_OK
01-30 10:55:50.513    6929-6929/com.startxlabs.conektademo I/Process﹕ Sending signal. PID: 6929 SIG: 9

If you require full log or any other query please tell me.

Best Regards
Deep

**Comment by javikin** [comment]
Are you using like the demo?

Also, you can use the last conekta realese library for all java:

https://github.com/conekta/conekta-java

**Comment by Dcodechef** [comment]
Hi Javikin,

Thanks for reply.
I tried to use the https://github.com/conekta/conekta-java library in Android for payment. Unfortunately I am facing few issues:

java.security.cert.CertificateException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
what is wrong in this Or how shell I implement this in Android (Procedure) ?

Regards,
Deep

**Comment by alfco333** [comment]
Hi everyone, first of all, great implementation of conekta, congrats, but I am facing the same problem  as Dcodechef using the library, so I want to know if you found a solution, any advice is welcome, thanks in advance.
